version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/crielly/mongosnap
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run:
          name: get dependencies for running tests
          command: |
            mkdir -p $TEST_RESULTS
            go get github.com/jstemmer/go-junit-report
            git branch -u origin ${CIRCLE_BRANCH}
            go get -u
            sudo apt-get install python-pip
            pip install awscli

      - run:
          name: Run Unit Tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
          
      - run:
          name: Build mongosnap binary
          command: |
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
            make build

      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "codedeploy" ]; then
              aws s3 sync dist/ s3://tastycidr-mongosnap-us-east-1 --delete
            else
              echo "Not master branch so not deploying"
            fi
