version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/crielly/mongosnap
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run:
          name: get dependencies for running tests
          command: |
            sudo apt-get install python-pip
            sudo pip install awscli
            mkdir -p $TEST_RESULTS
            go get github.com/jstemmer/go-junit-report
            git branch -u origin ${CIRCLE_BRANCH}
            go get -u

      - run:
          name: Run Unit Tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
          
      - run:
          name: Build mongosnap binary and publish it to github as a release
          command: |
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
            make build
            make publish
            aws ssm put-parameter --name mongosnapversion --overwrite --value "$(make versioncheck)" --type String --region us-east-1
